#!/bin/bash

function clean_copy { # $1: file1 $2: file2 $3:file_right
      rm -fdr $2
    if [[ -r $1 ]]; then
      cp -ap $1 "`dirname $2`/"
    else
      affich_text "Modification temporaire des droits" 1
      chmod +r $1
      cp -ap $1 "`dirname $2`/"
      chmod $3 $1 $2
    fi

}
function diff_file {
  case $1 in
    pdf) local pdf1=pdftotext $2 ; local pdf2=pdftotext $3; affich_text "`diff $pdf1 $pdf2`" 1;;
    txt) tmp=`diff $2 $3` ; affich_text "$tmp" 1 ;;
    *) ;;
  esac
}

function journal_edit { #$1= journal_path $2=data $3=filename1
  if [[ `cat $1 | grep -c $3` -gt 0 ]] ; then
    sed -i 's|.*'"$3"'.*|'"$2"'|' "$1"
  else
    echo $2 >> $1
  fi
}

function type_fich {
  if [[ -f $1 ]]; then
    typeFich="Fichier ordinaire"
  elif [[ -d $1 ]]; then
      typeFich="Dossier (`ls -1 $1 | wc -l` sous-fichiers)"
    else
      typeFich="Autre."
  fi

  echo "$typeFich"
}
