#!/bin/bash

function clean_copy { # $1: file1 $2: file2 $3:file_right

  if [[ (-r $1) && (-w $2) ]] ; then
    cp -p $1 $2
  else
    affich_text "Modification temporaire des droits" 1
    chmod +r $1
    chmod +w $2

    cp -p $1 $2
    chmod $3 $1 $2
  fi

}
function diff_file {
  case $1 in
    pdf) local pdf1=pdftotext $2 ; local pdf2=pdftotext $3; diff pdf1 pdf2; break;;
    txt) diff $2 $3; break ;;
    *) break;;
  esac
}

function journal_edit { #$1= journal_path $2=data $3=filename1
  if [[ `cat $1 | grep -c $3` -gt 0 ]] ; then
    sed -i 's|.*'"$3"'.*|'"$2"'|' "$1"
  else
    echo $2 >> $1
  fi
}

function type_fich {
  if [[ -f $1 ]]; then
    typeFich="Fichier ordinaire"
  elif [[ -d $1 ]]; then
      typeFich="Dossier (`ls -1 $1 | wc -l` sous-fichiers)"
    else
      typeFich="Autre."
  fi

  echo "$typeFich"
}
